spring.application.name=api-gateway
server.port=${GATEWAY_PORT:8080}
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.client.service-url.defaultZone=http://${EUREKA_SERVER_HOST:discovery-server}:${EUREKA_SERVER_PORT:8761}/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Swagger UI
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
# Swagger UI - Route Management
springdoc.swagger-ui.urls[0].name=Route Management
springdoc.swagger-ui.urls[0].url=/api/route-management/v3/api-docs
# Swagger UI - User Service
springdoc.swagger-ui.urls[1].name=User Service
springdoc.swagger-ui.urls[1].url=/api/user-management/v3/api-docs
# Swagger UI - Auth Service
springdoc.swagger-ui.urls[2].name=Auth Service
springdoc.swagger-ui.urls[2].url=/api/auth/v3/api-docs

# Swagger UI - Assign Driver Service
springdoc.swagger-ui.urls[3].name=Assign driver Service
springdoc.swagger-ui.urls[3].url=/api/assign-driver/v3/api-docs


spring.cloud.gateway.httpclient.connect-timeout=5000
spring.cloud.gateway.httpclient.response-timeout=10s
spring.cloud.loadbalancer.retry.enabled=true

server.forward-headers-strategy=native