spring.application.name=api-gateway
server.port=${GATEWAY_PORT:8080}
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.client.service-url.defaultZone=http://${EUREKA_SERVER_HOST:discovery-server}:${EUREKA_SERVER_PORT:8761}/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Spring Cloud Gateway Configuration
# Route management service
spring.cloud.gateway.routes[0].id=gtu-route-management-service
spring.cloud.gateway.routes[0].uri=lb://gtu-route-management-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/route-management/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/route-management/(?<segment>.*), /$\{segment}


# Swagger UI
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.urls[0].name=Route Management
springdoc.swagger-ui.urls[0].url=/api/route-management/v3/api-docs




spring.cloud.gateway.httpclient.connect-timeout=5000
spring.cloud.gateway.httpclient.response-timeout=10s
spring.cloud.loadbalancer.retry.enabled=true

server.forward-headers-strategy=native